name: CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  ubuntu-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: building
        shell: pwsh
        run: |
          ${{secrets.TK_CLONE}}
          ${{secrets.LINUX_BUILDING}}
